### ISSUE TITLE
Not sure about this "to queue" since we don't have it , but looks like its not picking up the posted message, i will update here if i find any resolution

### ISSUE THREAD

**Issue by itsme31** [karthikpnsy/activemq-send-receive-camel-main#1]
https://github.com/karthikpnsy/activemq-send-receive-camel-main/blob/9417a526a9aa9e6d7cb8a63305c1697168f3dab7/activemq-send-receive-camel-main/src/main/java/com/karthik/routes/ActiveMQMsgConsumerRoute.java#L21

**Comment by karthikpnsy** [comment]
Please refer the branch code this will send every 6 seconds message to receivequeue( you need to update receivequeue name)
